#ifndef PBASE_IO_STL_H
#define PBASE_IO_STL_H

#include "pbase/error.h"
#include "pbase/types/cloud.h"
#include "pbase/types/meshindices.h"

/** Saves an stl mesh */
pError p_io_save_mesh_stl(pCloud points, pMeshIndices indices, const char *file, bool ascii);

/** Loads an stl mesh, pMeshIndices can be generated by p_mesh_indices_new_count_up(out_points.size/3) */
pError p_io_load_mesh_stl(pCloud *out_points, pMeshIndices *out_opt_indices, const char *file);


#endif //PBASE_IO_STL_H
