#include "helper.h"
#include "pbase/io/stl.h"

//
// private
//

static String generate_ascii(pCloud cloud, pMeshIndices indices) {
    if(!p_cloud_valid(cloud) || !p_mesh_indices_valid(indices)) {
        log_error("p_io_save_stl failed, cloud or indices are invalid");
        p_error_set("Invalid parameters");
        return string_new_invalid();
    }

    // to print in C style (3.14, instead of 3,14 on some machines)
    setlocale(LC_ALL, "C");

    String data = string_new(512);
    String *s = &data;

    string_append(s, strc("solid pbase_io_stl (Meshed)\n"));
    for(int t=0; t<indices.size; t++) {
        string_append(s, strc("  facet normal "));
        vec3 a = cloud.data[indices.data[t].v0].xyz;
        vec3 b = cloud.data[indices.data[t].v1].xyz;
        vec3 c = cloud.data[indices.data[t].v2].xyz;
        append_vec3(s, triangle_normal(a, b, c));
        string_append(s, strc("\n    outer loop"));
        for(int abc=0; abc<3; abc++) {
            string_append(s, strc("\n      vertex "));
            append_vec3(s, (vec3[]) {a, b, c}[abc]);
        }
        string_append(s, strc("\n    endloop\n  endfacet\n"));
    }
    string_append(s, strc("endsolid Mesh\n"));

    return data;
}

static String generate_binary(pCloud cloud, pMeshIndices indices) {
    if(!p_cloud_valid(cloud) || !p_mesh_indices_valid(indices))
        return string_new_invalid();

    size_t header_size = 80 + 4;
    size_t triangle_size = 50;
    size_t file_size = header_size + triangle_size * indices.size;

    String data = string_new(file_size);
    data.size = file_size;

    memset(data.data, 0, 80);
    sprintf(data.data, "%s", "STL binary generated by pbase_io_stl");

    Str_s s = data.str;
    s.data+=80;
    s.size-=80;

    // stl is little endian
    s = str_feed_uint32_binary_le(s, indices.size);

    for(int t=0; t<indices.size; t++) {
        vec3 a = cloud.data[indices.data[t].v0].xyz;
        vec3 b = cloud.data[indices.data[t].v1].xyz;
        vec3 c = cloud.data[indices.data[t].v2].xyz;
        s = feed_vec3_le(s, triangle_normal(a, b, c));
        for(int abc=0; abc<3; abc++) {
            s = feed_vec3_le(s, (vec3[]) {a, b, c}[abc]);
        }
        s = str_feed_uint16_binary_le(s, 0);    // Attribute byte count
    }

    if(s.data != data.data + file_size || s.size != 0) {
        log_error("p_io_stl failed to generate binary");
    }

    return data;
}

//
// public
//

pError p_io_save_mesh_stl(pCloud points, pMeshIndices indices, const char *file, bool ascii) {
    if(!str_ends_with(strc(file), strc(".stl")) && !str_ends_with(strc(file), strc(".STL"))) {
        log_warn("p_io_save_mesh_stl: file does not end with .stl: %s", file);
    }

    String data;
    if(ascii)
        data = generate_ascii(points, indices);
    else
        data = generate_binary(points, indices);

    if(!file_write(file, data.str, ascii)) {
        log_error("p_io_save_mesh_stl failed to write file");
        p_error_assume();
    }

    string_kill(&data);
    return p_error();
}
